# ファイル操作
# [[plugins]]
# repo = 'Shougo/unite.vim'

# [[plugins]]
# repo = 'Shougo/neomru.vim'

# ファイルをtree表示
# [[plugins]]
# repo = 'scrooloose/nerdtree'

# Rails向けのコマンド
# [[plugins]]
# repo = 'tpope/vim-rails'

# Ruby補完
# [[plugins]]
# repo = 'tpope/vim-endwise'

# コメントON/OFF
# [[plugins]]
# repo = 'tomtom/tcomment_vim'

# 行末の半角スペースの可視化
# [[plugins]]
# repo = 'bronson/vim-trailing-whitespace'
