{ pkgs }:
[
  {
    home.packages = with pkgs; [
      age
      bun
      container
      curl
      deno
      docker
      docker-credential-helpers
      dotenvx
      ghq
      google-cloud-sdk
      graphviz
      mactop
      nix-search-cli
      nixfmt-rfc-style
      nodejs_22
      nvfetcher
      php83
      php83Packages.composer
      pinentry_mac
      sops
      terminal-notifier
      tig
      uv
      wget
      _1password-cli
    ];
  }
]
