keys:
  # users
  - &admin age1r9r7z5crn6v77ye6psxvf24mdtmxgnng8xuvdryhckpjpmlyhdyqh8j2pc
  - &sc age1hd03r99ut6kj64y9kxnekggxkzyzav985uzxes35v9e5cfjtp4fs6gelkf
  # machines
  - &mac age16hjw8qjvc0aakun7e4j9kfpzl787vqcvsfaqyr4u488vlyema5lsu95evr
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin
          - *sc
          - *mac
