[fish-ghq]
src.git = "https://github.com/decors/fish-ghq"
src.branch = "master"
fetch.github = "decors/fish-ghq"

[tmux-agent-sidebar]
src.github = "hiroppy/tmux-agent-sidebar"
fetch.github = "hiroppy/tmux-agent-sidebar"

[direnv-nvim]
src.git = "https://github.com/NotAShelf/direnv.nvim"
src.branch = "main"
fetch.github = "NotAShelf/direnv.nvim"
