# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  arto-vim = {
    pname = "arto-vim";
    version = "b05936238ff835ceca43442bf4ab8e843e73815c";
    src = fetchFromGitHub {
      owner = "arto-app";
      repo = "arto.vim";
      rev = "b05936238ff835ceca43442bf4ab8e843e73815c";
      fetchSubmodules = false;
      sha256 = "sha256-/Rk/t7Hm/VTa1KQptzd+1sZIiRR2l++tA98DSe9uwV4=";
    };
    date = "2026-02-01";
  };
  fish-ghq = {
    pname = "fish-ghq";
    version = "cafaaabe63c124bf0714f89ec715cfe9ece87fa2";
    src = fetchFromGitHub {
      owner = "decors";
      repo = "fish-ghq";
      rev = "cafaaabe63c124bf0714f89ec715cfe9ece87fa2";
      fetchSubmodules = false;
      sha256 = "sha256-6b1zmjtemNLNPx4qsXtm27AbtjwIZWkzJAo21/aVZzM=";
    };
    date = "2021-07-16";
  };
}
