# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  direnv-nvim = {
    pname = "direnv-nvim";
    version = "9258f9f10c4c729d8296fce0e3ecb12543daad06";
    src = fetchFromGitHub {
      owner = "NotAShelf";
      repo = "direnv.nvim";
      rev = "9258f9f10c4c729d8296fce0e3ecb12543daad06";
      fetchSubmodules = false;
      sha256 = "sha256-b5PpmkYWaDGLNcu+36tRR5ycATHYBjs9WrV8/jfmooQ=";
    };
    date = "2026-06-29";
  };
  fish-ghq = {
    pname = "fish-ghq";
    version = "cafaaabe63c124bf0714f89ec715cfe9ece87fa2";
    src = fetchFromGitHub {
      owner = "decors";
      repo = "fish-ghq";
      rev = "cafaaabe63c124bf0714f89ec715cfe9ece87fa2";
      fetchSubmodules = false;
      sha256 = "sha256-6b1zmjtemNLNPx4qsXtm27AbtjwIZWkzJAo21/aVZzM=";
    };
    date = "2021-07-16";
  };
  gh-pr-graph = {
    pname = "gh-pr-graph";
    version = "v0.15.1";
    src = fetchFromGitHub {
      owner = "orangain";
      repo = "gh-pr-graph";
      rev = "v0.15.1";
      fetchSubmodules = false;
      sha256 = "sha256-APYijprR9xWw2Y6BMZRiA5xeTS3zeIbXD45ymYgZqSM=";
    };
  };
  hydro = {
    pname = "hydro";
    version = "f130b55ee3eaf099eccf588e2a62e5447068d120";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "hydro";
      rev = "f130b55ee3eaf099eccf588e2a62e5447068d120";
      fetchSubmodules = false;
      sha256 = "sha256-Dfq974KpD1mtQKznIlkXfZfDnSF/4MfLTA18Ak0LADE=";
    };
    date = "2026-02-24";
  };
  matt-pocock-skills = {
    pname = "matt-pocock-skills";
    version = "2ab958093e83e0ec752e6c1c5932da465bf23e0c";
    src = fetchFromGitHub {
      owner = "mattpocock";
      repo = "skills";
      rev = "2ab958093e83e0ec752e6c1c5932da465bf23e0c";
      fetchSubmodules = false;
      sha256 = "sha256-dQtG6usJWlg/FqTajrjcs8GSdymH92WsgLiUaCfvKPA=";
    };
    date = "2026-07-28";
  };
  tcmux = {
    pname = "tcmux";
    version = "v0.4.0";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "tcmux";
      rev = "v0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-joQSbM0nGjKD0Yxp5JYXIluHyjcRU8HnAFJZ8JOmSTE=";
    };
  };
}
