memodir = "/Users/kohei/.config/memo/_posts"
editor = "/usr/local/bin/vim"
column = 20
width = 0
selectcmd = "fzf"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
memotemplate = "/Users/kohei/.config/memo/template.txt"
assetsdir = "."
pluginsdir = "/Users/kohei/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
