-- base
vim.o.ruler = true
vim.o.number = true
vim.o.relativenumber = true
vim.o.title = true
vim.o.visualbell = true
vim.o.termguicolors = true
vim.o.expandtab = true
vim.o.tabstop = 4
vim.o.smarttab = true
vim.o.shiftwidth = 2
vim.o.softtabstop = 2
vim.o.smartindent = true
-- vim.o.cursorline = true
vim.o.wildmenu = true
vim.o.wrap = true
vim.o.whichwrap = "b,s,h,l,<,>,~,[,]"
vim.o.display = "lastline"
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.list = true
vim.o.listchars = "tab:»-,space:･,trail:-,eol:↲,extends:»,precedes:«,nbsp:%"
vim.o.wildmode = "full"
vim.o.showcmd = true
vim.o.showtabline = 2
vim.o.showmode = false
vim.o.clipboard = "unnamed"
vim.o.backspace = "indent,eol,start"
vim.o.nrformats = ""
vim.o.pumheight = 10
vim.o.showmatch = true
vim.o.matchtime = 1
vim.o.hidden = true
vim.o.ttyfast = true
vim.o.lazyredraw = true
vim.g.nobackup = true
vim.g.nowritebackup = true
vim.g.noundofile = true
vim.g.noswapfile = true
vim.o.updatetime = 100
vim.o.signcolumn = "yes"
-- vim.o.spell = true
-- vim.o.spelllang = "en,cjk"
vim.cmd("filetype plugin indent on")
