test: ENC[AES256_GCM,data:1VR2G9qLPg==,iv:ZyvLrU1V+vy3Rfq9PBOyAlXqh9gi/CHAvoj5pFaIzNI=,tag:peTZ3PuXFFggLNQU3+Ju4w==,type:str]
sops:
    age:
        - recipient: age1r9r7z5crn6v77ye6psxvf24mdtmxgnng8xuvdryhckpjpmlyhdyqh8j2pc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMk1STzdaQk9KaWtVWmh1
            Z0dZWFpEU2Q1RnFnVWZBdW5ISVJHOW5ZSEFjCnZsM0VlNzhRS1N1OHZrMkdpd3Jh
            MGp0My9Zd3hlbklxTit1UnVnVlpMYVkKLS0tIDdHRXoyWERaQkhyck93ekdjY0pD
            cHk0UjZCcVhHUFhPTTZNNHlLMHhmQmsKfPZPcKqNDaerAEcjhq7mUc1ZBgdOmKOw
            NWWDDyd6glpB0sacGR/c+IJ4W8GeyK0alue538zp7a7JVWsInAsE8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hd03r99ut6kj64y9kxnekggxkzyzav985uzxes35v9e5cfjtp4fs6gelkf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UktwRkgvV0VvKzhtYkxM
            MDVuTTdzT2lWc2tGWmxLdnJ6RXdqZ1B3VFdJCjFEcGR5dy85am1ZRVZZbklncFNr
            MlAxMUVzZHB2WDRWWXlWSll3cTRhQ3MKLS0tIDEwRFl5K3VqUUw1bC84aHNqdW1H
            YjBTakZMQ1ZDSjA3cXZKaEs4cmpkTWMKCmtWioO/9fI1wqckrUi6qZ+NxwOgV4vG
            YFjeZCD6DgbZTNIYv+c+/Jxj5/HqFezxmalmUWt74Xu9/bFqLzcqIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16hjw8qjvc0aakun7e4j9kfpzl787vqcvsfaqyr4u488vlyema5lsu95evr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRTRYcDNpejR4Q2EvcytE
            bVByOVRQdG9nK1JrUjVMeFM1SUljdFVsWVgwCm1rNFE5alhWNjZWY2NxV3FxZUdY
            aXpEK0daV0pBV0NLand2MjUyMysvRjQKLS0tIG8xYmw5SnNZWFRjNDFyQjdQNWJr
            VXNLOFM2TWpzVGd1dThjL3RxdngzaEUKxWeh1but6w6jreLNHSILgrZ9rrWTHeAo
            a7Wd9i+jC6NxCUBha1xs1u6pmgAJR4ZBkqkASbJVZOr+I+aYA9j3lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-24T07:58:29Z"
    mac: ENC[AES256_GCM,data:sO9YJ0mpMASn9CzFITx7CEpTmr48alZ3xjO703a6kq1FVHNAWEMT/v1NUO64VWh82U6QGcPLSFb0Tp+IRNX6mbuTZ7XlPd3cof81kgIeuMI9uyh5I7uIYjUXG6hJaFH5m/e2hq0cnO0EfdrKK8JYxt5IWEnPw8Yu9eLM+3uS+HU=,iv:uQHdjKRHdHOvCbSG8HOdne26zigwIlS6GjtSURLQi8o=,tag:5R7S6Aea2MxnLpQBnwDFWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
