test: ENC[AES256_GCM,data:1VR2G9qLPg==,iv:ZyvLrU1V+vy3Rfq9PBOyAlXqh9gi/CHAvoj5pFaIzNI=,tag:peTZ3PuXFFggLNQU3+Ju4w==,type:str]
sops:
    age:
        - recipient: age1r9r7z5crn6v77ye6psxvf24mdtmxgnng8xuvdryhckpjpmlyhdyqh8j2pc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZTdMM2QyZWZQaWRmUGtR
            bVgrZTBCbDhRNmRmb2FzU3JWaGR5NHIvSzNvCks0WnhacWNJeEtCSjFMRHF3OFVy
            VXA0U0Ntbm04a00vekxOTitSMHFnbUEKLS0tIFlFTHBpYUJzL1pSMFJGNThKTlJ3
            dTlBSGFjNlJOZmNTaU55SmVaSzZ2NlkKNoX/gL+rW0u/d7ZyrMH0GiVocxMbRQZb
            bxnoWG6iAMiE3Bg0XNBVS1JE7goDhdM0Dj3lrDgkVOR00QUFM4HADw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16hjw8qjvc0aakun7e4j9kfpzl787vqcvsfaqyr4u488vlyema5lsu95evr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMzU1d3ZjcEd3b3JZNXJx
            ZWlOTDFrb0dVTFRoQ0o5czB0blliTWFJdVZzCnZKLzQvV1JCUTMvK2phZG1jU1lw
            NE1pSmFxbVp2cWRCOWRDelRjdkJ0K0kKLS0tIGdqbzg5ZllyQTZSWXVKV0h6RXc5
            SWlzZTRDS3JlaUx0QjFhRmp1L1JMV0kKVdbeGP3peKIKuVLrG7rtwDEyC9kIcSPu
            vzk6vRhu6/wvKXpFTl8c+XHS4qZrIUmjqHWgbZgincWWEnmOqQpzSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-02T14:11:27Z"
    mac: ENC[AES256_GCM,data:6ckDMOQlkTrwFEcuQmFRVJyd+sV4b4vVBBkutXniXzhkR7PoFpNwhJBb4Rqb9ANyNbKe+4lVEznCh4IVdgOUa5RC77opjmIrRa+TdenMaG8Ar0ww3g3CfIITr0cDf8xtvUdp7FFpJR2gmgiRD7mS3PwAW9QGjKfmhheYKD4fJBY=,iv:6Sisox2lDBejXKsSZ7XcmhM06TSEqD75pi4NQnOQkuw=,tag:W72+UCkhD1PGcinhJA/5Ww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
