test: ENC[AES256_GCM,data:bfXd5Q==,iv:D9/fBaHKSz9wCm3/b6Zh0n2xGiRFLgnQtT7Y3Tg178k=,tag:vChoWKs17aaj+yM1K59xvA==,type:str]
sops:
    age:
        - recipient: age1r9r7z5crn6v77ye6psxvf24mdtmxgnng8xuvdryhckpjpmlyhdyqh8j2pc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISWVaUkpFNEx0cGo1dUli
            dGwwNDV2R0ZlamFNQis5YWdiZzRjbUowZms0CkxPVk5QSE0vY25KRHZVNHpJUTVi
            VUpvdGtoeG9RbW9aa2lDWUdHd3pqWGcKLS0tIEhVVHd3NzVlVFRzVWhTbzJxb2kx
            cE9TTzM2Nit4bU9TZXE4R290TmFGZzAKJUSkCc0Jig5txPGE5vz1XyvWX4KxjZSz
            6uEY31MkIZKsjdkbMb4iDC1gklz/rhnWTrijLLfBvHqjU1x81psFdw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16hjw8qjvc0aakun7e4j9kfpzl787vqcvsfaqyr4u488vlyema5lsu95evr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZHZOQzVyTzhHNHBwMG1K
            eDg3M1pQcGg4NkNNY2d4T29iUFplZkh0U3lBCllmVkxoWGc4dW5wZ3h4UEJJTDVO
            K1BaTXpkQUhLTGs3MkwxVjdSdlhVZlkKLS0tIFF5SGg5Nmp3VlF5UnpVZGIzVklT
            K3haanI0M2t1VWpLMTJlN2VGM3BZYWsKf5pg06+gDP/JsYQuQP9Zvv9cBkEwtdJY
            v71cOF5yqZLJHZ9dVKZ2ity/sXUCJcpLJJekFEI7lULUm3lsA2DuEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-20T15:22:12Z"
    mac: ENC[AES256_GCM,data:m57BcOWqLvcN0M3SSV28BOwvPwFqR0+nZrTUvRoRXTJhxGjlolfZRE31cCVZKHvllEJyI6mx+SkBWHA63gVDGFvOZtjkAP5Nqh1LtETFj73z/xRfS3sQrROHDitcIv/59F+yG/D6qJma+zB3rEBVJsCfxhkotC/KWt3gN74ln4o=,iv:PLUMK8ITVCPsuraHcVNyHco6I5zGvqm56wiMDjIlVc0=,tag:UBt3R8Rpb/JpEVf1xl7DFw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
