test: ENC[AES256_GCM,data:1VR2G9qLPg==,iv:ZyvLrU1V+vy3Rfq9PBOyAlXqh9gi/CHAvoj5pFaIzNI=,tag:peTZ3PuXFFggLNQU3+Ju4w==,type:str]
discord-bot-token: ENC[AES256_GCM,data:bm63ynvwDoJrjAd/rhodjUatdkKv7jnfNmKyFoHg3rthvo8xeHY5zMIs4nirO7htqFNJvRPS3BIya/TfkPvsb+H2IcK28ZCz,iv:TOvxLkZC7+6AJBFDeI/uujx/RoCiCUbso0vOVV6y6AI=,tag:kiaa72B5KzUQe4PJj+06Ig==,type:str]
sops:
    age:
        - recipient: age1r9r7z5crn6v77ye6psxvf24mdtmxgnng8xuvdryhckpjpmlyhdyqh8j2pc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VENjejA1YnNhNldVczMx
            d1A1WG1tUFR6VzV0SlROZGl1V2FQV29xQWlBCnJqa1NTdHNFNHU5RjRNT2dkYTla
            dHJid0VNQjdSSVc5NEtkbGF3K010TE0KLS0tIHBzQU9rM0h4OHJRek9OS0l4Wm1x
            SUJUVWxwTHNyVEhxSTNQeEJ1YUFERDAKt+AX9i5Lmjv+dAfmeW3TXJtYLiDP3gP8
            CcMMlytf0rOnkIP8ruKq0F8Pmy0F9GmVmieHq2dqc4l/EnHBQrKOeA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hd03r99ut6kj64y9kxnekggxkzyzav985uzxes35v9e5cfjtp4fs6gelkf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSc004RTRRZlFDSUtXVUh5
            K0MxVWFtQlpMc21FZUJYMGwwdlE0T3BwQTM0Ck5wb2pnaDlsejFSVVdBcHlsMUJ5
            NmlOelBrcC9nK0p5c2RiZVlWR21pNUUKLS0tIGUrdnpycFJrYVNnTVBvUXZGTWEv
            c05ZUUtHSWVzUWRvS3BLVGcyMTBkRXcKHNTs5CuOyMv8W6xBax/RBXyUrFku3Nyq
            rfCzvwQ0elLa2bVpizqkP5WClz8k+99vOC2VryfwMtU24aDNGPaDYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16hjw8qjvc0aakun7e4j9kfpzl787vqcvsfaqyr4u488vlyema5lsu95evr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNFBBR2hKdGRUMUFmQVds
            bnF3MjZEMzNPdWl1Mk5mZVdoeDRWd3pHUzJVCjBKbG1GMzErTDJuQjJCY0tEdVZP
            a3B3anBXcm1zcjlEYTV3K0g4WGlCUHMKLS0tIEU5cjNqcUgvNENKWXVNYWl3NmpE
            RXhrZ2d1NVNaMGovSng5bnBJdFhQdWsKU9hpHey0gZDL5Fds0qaMnhjJc+rfOThl
            i0TJQu8v3CCyKK7Ev44xq/pbwGt4ZZ0z3xueFNgtF3MoHk8Vc1/WgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sgdgpmndyyzz4zguf97uvppkprsfrklgn3t8cvdegtw8lh9h8fms7druqw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVlFHN3RzWTBTNVlGZkhY
            YkpDWFdPMkhXTjRma0crQTU4TlhTVVc4SUVRCkZVR1VxemZZZkpkMWd6UUJZSGRB
            aVlINGlCOEhCVEtyS0JncXhRdXdRWlkKLS0tIGFRUURLZjZ3NExKTEpPTExhOHVO
            L05sdFpDMFFBSnJuM0FidFN0Q3ZUMVEKxomS6cvKNXBzKRbGkc77XqDxTLwO5N31
            z5Zi6x/3CLtVzYomcPXuCaoE1xd73v8dKplygzMCsgzKRehDoQR58Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T04:09:05Z"
    mac: ENC[AES256_GCM,data:OgcBsf3lMHH4YsXCRhqwhs0HTxQQFavB8id9P6idi6r2F3UpsbLpzdkNcap1p4yz+7cXCnEH+uVf8elY1P8VjZPXAjQDNmWVyTzy2BsE5PQtg8wnwoGU6J2Y0vJJJ73GCO/DvkYVGy0Ab9bM3+jBtQGrelXjDjhTjwpq0gzTKrw=,iv:dhkP9TteHS16Vsfvqx6ydLRWQbQ/Yzm5DP9gryxSbiY=,tag:UQ/gUe5RMAIBQnALSwspOA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
